echo "LAUNCHING ---- GET READY!"
echo "       .__                       "
echo "______ |  |__ ______       _      █████  ██████   █████   ██████ ██   ██ ███████ ██████ "
echo "\____ \|  |  \\____  \    _| |_   ██   ██ ██   ██ ██   ██ ██      ██   ██ ██           ██ "
echo "|  |_> >   Y  \  |_> >  (_   _)  ███████ ██████  ███████ ██      ███████ █████    █████  "
echo "|   __/|___|  /   __/     |_|    ██   ██ ██      ██   ██ ██      ██   ██ ██      ██      "
echo "|__|        \/|__|               ██   ██ ██      ██   ██  ██████ ██   ██ ███████ ███████"
echo "shodan's POC for :: XSS in CSS"
echo " "
echo "Acessible from http://127.0.0.1:80"
docker run --name xssviacsspoc -d -p 80:80 xssviacss:1
